import { migrate } from "drizzle-orm/node-postgres/migrator";
import { db } from "./client.js";
import { pool, waitForDb } from "./pool.js";

// Applies any pending migrations from ./drizzle (generated by `pnpm db:generate`).
// Drizzle tracks what has run in its own table, so this is safe to re-run.
async function main(): Promise<void> {
  await waitForDb();
  await migrate(db, { migrationsFolder: "drizzle" });
  console.log("✓ migrations applied");
  await pool.end();
}

main().catch((err) => {
  console.error("migration failed:", err);
  process.exit(1);
});
